name = "iceperf-website"
pages_build_output_dir = "dist"
compatibility_date = "2024-04-22"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "iceperf-cache"
id = "aa575584b93c47298f2901efb92d7d72"
preview_id = "aa575584b93c47298f2901efb92d7d72"
